/* These tables will be used for other ingredient information
/* The table creation DDLs need to be executed PUB Schemas.*/
CREATE TABLE SGS_PROD_OTHING(ASSET_VERSION INTEGER NOT NULL,OTHING_ID varchar2(40),PRODUCT_ID varchar2(40),SITE_ID varchar2(40));

CREATE TABLE SGS_OTHING_CONTAINER(ASSET_VERSION INTEGER NOT NULL,
WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
BRANCH_ID 		VARCHAR2(40) NOT NULL,
IS_HEAD 		NUMBER(1) NOT NULL,
VERSION_DELETED 	NUMBER(1) NOT NULL,
VERSION_EDITABLE 	NUMBER(1) NOT NULL,
PRED_VERSION 		INTEGER NULL,
CHECKIN_DATE 		TIMESTAMP NULL,
OTHING_IDS varchar2(40),
LAST_MOD_DATE DATE NULL);

CREATE TABLE SGS_OTHING_LIST(ASSET_VERSION INTEGER NOT NULL,
OTHING_ID varchar2(40),
OTHING_IDS varchar2(40),
SEQUENCE_NUM varchar2(40));

CREATE TABLE SGS_OTHING_SITES(ASSET_VERSION INTEGER NOT NULL,
OTHING_ID varchar2(40),
SITE_ID varchar2(40));

CREATE TABLE SGS_OTHING_DETAILS(ASSET_VERSION INTEGER NOT NULL,
WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
BRANCH_ID 		VARCHAR2(40) NOT NULL,
IS_HEAD 		NUMBER(1) NOT NULL,
VERSION_DELETED 	NUMBER(1) NOT NULL,
VERSION_EDITABLE 	NUMBER(1) NOT NULL,
PRED_VERSION 		INTEGER NULL,
CHECKIN_DATE 		TIMESTAMP NULL,
OTHING_ID VARCHAR2(40),
BACK_IMAGE_LARGE VARCHAR2(100),
OTHING_NAME varchar2(400),
OTHING_LONGDESCRIP CLOB,
DISPLAY_IMAGE_SMALL VARCHAR2(100),
DISPLAY_TITLE varchar2(400),
DISPLAY_DESC CLOB,
LAST_MOD_DATE DATE	NULL);


ALTER TABLE SGS_ING_DETAILS drop column ING_DESCRIP;
ALTER TABLE SGS_ING_DETAILS ADD ING_DESCRIP CLOB ;
ALTER TABLE SGS_ING_DETAILS ADD BACK_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD ING_IMAGE_DESCRIP CLOB;
ALTER TABLE SGS_ING_DETAILS ADD ING_DESCRIP2 CLOB;
ALTER TABLE SGS_ING_DETAILS ADD ING_VIDEO VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD BADGE_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD ING_CERTI_DESCRIP CLOB;
ALTER TABLE SGS_ING_DETAILS ADD ING_CERTI_TITLE VARCHAR2(4000);
ALTER TABLE SGS_ING_DETAILS ADD DISPLAY_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD DISPLAY_TITLE VARCHAR2(4000);
ALTER TABLE SGS_ING_DETAILS ADD DISPLAY_DESC CLOB;

ALTER TABLE SGS_SOL_DETAILS drop column SOL_DESCRIP;
ALTER TABLE SGS_SOL_DETAILS ADD SOL_DESCRIP CLOB ;
ALTER TABLE SGS_SOL_DETAILS ADD BACK_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_SOL_DETAILS ADD IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_SOL_DETAILS ADD SOL_DESCRIP2 CLOB;
ALTER TABLE SGS_SOL_DETAILS ADD SOL_DESCRIP3 CLOB;
ALTER TABLE SGS_SOL_DETAILS ADD SYMPTOMS CLOB;
ALTER TABLE SGS_SOL_DETAILS ADD DISPLAY_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_SOL_DETAILS ADD DISPLAY_TITLE VARCHAR2(4000);
ALTER TABLE SGS_SOL_DETAILS ADD DISPLAY_DESC CLOB;

commit;
 
