--userInterests

CREATE TABLE SGS_PRODUCT_INTERESTS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 INTEREST_ID varchar2(40) NOT NULL,
 INTEREST_NAME varchar2(100),
 INTEREST_VALUE varchar2(100), 
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(INTEREST_ID,ASSET_VERSION) using index );


commit;

--drop table SGS_PRODUCT_INTERESTS;
--select * from SGS_PRODUCT_INTERESTS; 

 CREATE TABLE SGS_PRODUCT_INTERESTS_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 INTEREST_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(INTEREST_ID,SITE_ID,ASSET_VERSION) using index );
 
commit;
--drop table SGS_PRODUCT_INTERESTS_SITES;
--select * from SGS_PRODUCT_INTERESTS_SITES;


---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------

--userHealthConcerns

CREATE TABLE SGS_HEALTH_CONCERNS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 HEALTH_CONCERN_ID varchar2(40) NOT NULL,
 HEALTH_CONCERN_NAME varchar2(100),
 HEALTH_CONCERN_VALUE varchar2(100), 
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(HEALTH_CONCERN_ID,ASSET_VERSION) using index );


commit;

--drop table SGS_HEALTH_CONCERNS;
--select * from SGS_HEALTH_CONCERNS; 

 
CREATE TABLE SGS_HEALTH_CONCERNS_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 HEALTH_CONCERN_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(HEALTH_CONCERN_ID,SITE_ID,ASSET_VERSION) using index );
 
commit;
--drop table SGS_HEALTH_CONCERNS_SITES;
--select * from SGS_HEALTH_CONCERNS_SITES;



