SET DEFINE OFF;
ALTER TABLE COM_PUB.SGS_PRODUCT ADD DISPLAY_TITLE varchar2(254);
ALTER TABLE COM_PUB.SGS_PRODUCT ADD PROD_DIRECTION CLOB;
ALTER TABLE COM_PUB.SGS_PRODUCT ADD PROD_INGREDIENT CLOB;
ALTER TABLE COM_PUB.SGS_PRODUCT ADD PROD_SOLUTION CLOB;
ALTER TABLE COM_PUB.SGS_PRODUCT ADD SMALL_IMAGE varchar2(254);
ALTER TABLE COM_PUB.SGS_PRODUCT ADD LARGE_IMAGE varchar2(254);
ALTER TABLE COM_PUB.SGS_PRODUCT ADD MEDIUM_IMAGE varchar2(254);
ALTER TABLE COM_PUB.SGS_PRODUCT ADD THUMBNAIL_IMAGE varchar2(254);
ALTER TABLE COM_PUB.SGS_PRODUCT ADD PRODBACK_IMAGE varchar2(254);
ALTER TABLE COM_PUB.SGS_SKU ADD DISPLAY_TITLE varchar2(254);
ALTER TABLE COM_PUB.SGS_SKU ADD SMALL_IMAGE varchar2(254);
ALTER TABLE COM_PUB.SGS_SKU ADD LARGE_IMAGE varchar2(254);
ALTER TABLE COM_PUB.SGS_SKU ADD MEDIUM_IMAGE varchar2(254);
ALTER TABLE COM_PUB.SGS_SKU ADD THUMBNAIL_IMAGE varchar2(254);

 CREATE TABLE COM_PUB.SGS_PROD_BADGE(
 ASSET_VERSION 	INTEGER NOT NULL,
 BADGE_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(54), PRIMARY KEY(PRODUCT_ID,SITE_ID,ASSET_VERSION) using index tablespace USERS
 );
 CREATE TABLE COM_PUB.SGS_PRD_TESTI(
 ASSET_VERSION 	INTEGER NOT NULL,
 TESTI_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(54), PRIMARY KEY(PRODUCT_ID,SITE_ID,ASSET_VERSION) using index tablespace USERS
 );
 
CREATE TABLE COM_PUB.SGS_BADGES(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 BADGE_ID varchar2(40),
 BADGE_NAME varchar2(40),
 BADGE_DESCRIP varchar2(400),
 BADGE_IMAGE varchar2(254),
 LAST_MOD_DATE DATE	NULL,PRIMARY KEY(BADGE_ID,ASSET_VERSION) using index tablespace USERS);

 
 CREATE TABLE COM_PUB.SGS_BADGES_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 BADGE_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(BADGE_ID,SITE_ID,ASSET_VERSION) using index tablespace USERS );
 
 
 CREATE TABLE COM_PUB.SGS_TESTI_CONTAINER(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 TESTI_IDS varchar2(40),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(TESTI_IDS,ASSET_VERSION) using index tablespace USERS);
 
 CREATE TABLE COM_PUB.SGS_TESTI_LIST(
 ASSET_VERSION 		INTEGER NOT NULL,
 TESTI_ID varchar2(40),
 TESTI_IDS varchar2(40),
 SEQUENCE_NUM varchar2(40),PRIMARY KEY(TESTI_IDS,SEQUENCE_NUM,ASSET_VERSION) using index tablespace USERS);
 
 CREATE TABLE COM_PUB.SGS_TESTI(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 TESTI_ID varchar2(40),
 TESTI_NAME varchar2(40),
 TESTI_DESCRIP varchar2(400),
 TESTI_IMAGE varchar2(254),
 LAST_MOD_DATE DATE	NULL, PRIMARY KEY(TESTI_ID,ASSET_VERSION) using index tablespace USERS);
 
 CREATE TABLE COM_PUB.SGS_TESTI_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 TESTI_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(TESTI_ID,SITE_ID,ASSET_VERSION) using index tablespace USERS );
 
 CREATE TABLE COM_PUB.SGS_PRD_CHLDSKU_RELN(
 ASSET_VERSION 		INTEGER NOT NULL,
 SKUCH_PROD_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(SKUCH_PROD_ID,SITE_ID,ASSET_VERSION) using index tablespace USERS);
 
 CREATE TABLE COM_PUB.SGS_PRD_CHLDSKU_CONTAINER(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 SKUCH_PROD_IDS varchar2(40),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(SKUCH_PROD_IDS,ASSET_VERSION) using index tablespace USERS);
 
 CREATE TABLE COM_PUB.SGS_PRD_CHLDSKU_LIST(
 ASSET_VERSION 		INTEGER NOT NULL,
 SKUCH_PROD_IDS varchar2(40),
 CHILDSKU_ID varchar2(40),
 SEQUENCE_NUM varchar2(40),PRIMARY KEY(SKUCH_PROD_IDS,SEQUENCE_NUM,ASSET_VERSION) using index tablespace USERS);
 
 
CREATE TABLE COM_PUB.SGS_PROD_SOL(
 ASSET_VERSION 		INTEGER NOT NULL,
 SOL_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(SOL_ID,SITE_ID,ASSET_VERSION) using index tablespace USERS );
 
 CREATE TABLE COM_PUB.SGS_SOL_CONTAINER(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 SOL_IDS varchar2(40),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(SOL_IDS,ASSET_VERSION) using index tablespace USERS);
 
 CREATE TABLE COM_PUB.SGS_SOL_LIST(
 ASSET_VERSION 		INTEGER NOT NULL,
 SOL_ID varchar2(40),
 SOL_IDS varchar2(40),
 SEQUENCE_NUM varchar2(40),PRIMARY KEY(SOL_ID,SEQUENCE_NUM,ASSET_VERSION) using index tablespace USERS);
 
 CREATE TABLE COM_PUB.SGS_SOL_DETAILS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 SOL_ID varchar2(40),
 SOL_NAME varchar2(400),
 SOL_DESCRIP varchar2(400),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(SOL_ID,ASSET_VERSION) using index tablespace USERS);
 CREATE TABLE COM_PUB.SGS_SOL_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 SOL_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(SOL_ID,SITE_ID,ASSET_VERSION) using index tablespace USERS);

 CREATE TABLE COM_PUB.SGS_PROD_ING(
 ASSET_VERSION 		INTEGER NOT NULL,
 ING_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(ING_ID,SITE_ID,ASSET_VERSION) using index tablespace USERS );
 CREATE TABLE COM_PUB.SGS_ING_CONTAINER(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 ING_IDS varchar2(40),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(ING_IDS,ASSET_VERSION) using index tablespace USERS);
 
 CREATE TABLE COM_PUB.SGS_ING_LIST(
 ASSET_VERSION 		INTEGER NOT NULL,
 ING_ID varchar2(40),
 ING_IDS varchar2(40),
 SEQUENCE_NUM varchar2(40),PRIMARY KEY(ING_ID,SEQUENCE_NUM,ASSET_VERSION) using index tablespace USERS);
 
 CREATE TABLE COM_PUB.SGS_ING_DETAILS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 ING_ID varchar2(40),
 ING_NAME varchar2(400),
 ING_DESCRIP varchar2(400),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(ING_ID,ASSET_VERSION) using index tablespace USERS);
 CREATE TABLE COM_PUB.SGS_ING_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 ING_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(ING_ID,SITE_ID,ASSET_VERSION) using index tablespace USERS);
 
CREATE TABLE COM_PUB.COMVITA_PROD_SITE_TRANSLATIONS(
ASSET_VERSION 		INTEGER NOT NULL,
PRODUCT_ID  VARCHAR2(40),
TRANSLATION_ID VARCHAR2(80),PRIMARY KEY(PRODUCT_ID,TRANSLATION_ID) using index tablespace USERS);
 
CREATE TABLE COM_PUB.COMVITA_PROD_TRANSLATIONS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
TRANSLATION_ID                   VARCHAR2(80), 
SITE_ID                          VARCHAR2(40),  
LOCALE_ID                        VARCHAR2(40), 
DISPLAY_NAME                     VARCHAR2(254), 
DESCRIPTION                     VARCHAR2(1200),
TITLE                           VARCHAR2(40),
DIR_DESC                        VARCHAR2(1200),
SOL_DESC                        VARCHAR2(1200),
ING_ESC                         VARCHAR2(1200),      
PRICE_RANGEDESC                 VARCHAR2(1200),      
WEBONLY                         NUMBER(1),
WEBOFFERED          			NUMBER(1),
PRODDISABLE                     NUMBER(1),
SKULOWPRICE                     VARCHAR2(40),
SKUHIGHPRICE                    VARCHAR2(40),
LAST_MOD_DATE DATE	NULL,PRIMARY KEY(SITE_ID,TRANSLATION_ID,ASSET_VERSION) using index tablespace USERS);
 
 
 /*
 Start adding new table 
 */
 /*
DROP TABLE COM_PUB.SGS_PROD_SOL;
DROP TABLE COM_PUB.SGS_SOL_CONTAINER;
DROP TABLE COM_PUB.SGS_SOL_LIST;
DROP TABLE COM_PUB.SGS_SOL_DETAILS;
DROP TABLE COM_PUB.SGS_SOL_SITES;
DROP TABLE COM_PUB.SGS_PROD_ING;
DROP TABLE COM_PUB.SGS_ING_CONTAINER;
DROP TABLE COM_PUB.SGS_ING_LIST;
DROP TABLE COM_PUB.SGS_ING_DETAILS;
DROP TABLE COM_PUB.SGS_ING_SITES;
DROP TABLE COM_PUB.COMVITA_PROD_SITE_TRANSLATIONS;
DROP TABLE COM_PUB.COMVITA_PROD_TRANSLATIONS;

DROP TABLE COM_PUB.SGS_PROD_BADGE;
DROP TABLE COM_PUB.SGS_PRD_TESTI;
DROP TABLE COM_PUB.SGS_BADGES;
DROP TABLE COM_PUB.SGS_BADGES_SITES;
DROP TABLE COM_PUB.SGS_TESTI_CONTAINER;
DROP TABLE COM_PUB.SGS_TESTI_LIST;
DROP TABLE COM_PUB.SGS_TESTI;
DROP TABLE COM_PUB.SGS_TESTI_SITES;
DROP TABLE COM_PUB.SGS_PRD_CHLDSKU_RELN;
DROP TABLE COM_PUB.SGS_PRD_CHLDSKU_CONTAINER;
DROP TABLE COM_PUB.SGS_PRD_CHLDSKU_LIST;

ALTER TABLE COM_PUB.SGS_PRODUCT DROP COLUMN DISPLAY_TITLE ;
ALTER TABLE COM_PUB.SGS_PRODUCT DROP COLUMN PROD_DIRECTION;
ALTER TABLE COM_PUB.SGS_PRODUCT DROP COLUMN PROD_INGREDIENT;
ALTER TABLE COM_PUB.SGS_PRODUCT DROP COLUMN PROD_SOLUTION;
ALTER TABLE COM_PUB.SGS_PRODUCT DROP COLUMN SMALL_IMAGE;
ALTER TABLE COM_PUB.SGS_PRODUCT DROP COLUMN LARGE_IMAGE;
ALTER TABLE COM_PUB.SGS_PRODUCT DROP COLUMN MEDIUM_IMAGE;
ALTER TABLE COM_PUB.SGS_PRODUCT DROP COLUMN THUMBNAIL_IMAGE;
ALTER TABLE COM_PUB.SGS_PRODUCT DROP COLUMN PRODBACK_IMAGE;
ALTER TABLE COM_PUB.SGS_SKU DROP COLUMN DISPLAY_TITLE ;
ALTER TABLE COM_PUB.SGS_SKU DROP COLUMN SMALL_IMAGE;
ALTER TABLE COM_PUB.SGS_SKU DROP COLUMN LARGE_IMAGE;
ALTER TABLE COM_PUB.SGS_SKU DROP COLUMN MEDIUM_IMAGE;
ALTER TABLE COM_PUB.SGS_SKU DROP COLUMN THUMBNAIL_IMAGE;*/
 
COMMIT;