--userHearAboutUs

CREATE TABLE SGS_HEAR_ABOUT_US(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 HEAR_ABOUT_US_ID varchar2(40) NOT NULL,
 HEAR_ABOUT_US_NAME varchar2(100),
 HEAR_ABOUT_US_VALUE varchar2(100), 
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(HEAR_ABOUT_US_ID,ASSET_VERSION) using index );


commit;

--drop table SGS_HEAR_ABOUT_US;
--select * from SGS_HEAR_ABOUT_US; 

 CREATE TABLE SGS_HEAR_ABOUT_US_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 HEAR_ABOUT_US_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(HEAR_ABOUT_US_ID,SITE_ID,ASSET_VERSION) using index );
 
commit;
--drop table SGS_HEAR_ABOUT_US_SITES;
--select * from SGS_HEAR_ABOUT_US_SITES;

