--userHearAboutUs

CREATE TABLE SGS_HEAR_ABOUT_US(
 HEAR_ABOUT_US_ID varchar2(40) NOT NULL,
 HEAR_ABOUT_US_NAME varchar2(100),
 HEAR_ABOUT_US_VALUE varchar2(100), 
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(HEAR_ABOUT_US_ID) using index );


commit;

--drop table SGS_HEAR_ABOUT_US;
--select * from SGS_HEAR_ABOUT_US; 

 CREATE TABLE SGS_HEAR_ABOUT_US_SITES(
 HEAR_ABOUT_US_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(HEAR_ABOUT_US_ID,SITE_ID) using index );
 
commit;
--drop table SGS_HEAR_ABOUT_US_SITES;
--select * from SGS_HEAR_ABOUT_US_SITES;

