/* This script will run only on PUB */
Drop Table SGS_PRD_CHLDSKU_RELN;
Drop Table SGS_PRD_CHLDSKU_CONTAINER;
Drop Table SGS_PRD_CHLDSKU_LIST;
CREATE TABLE SGS_SKU_SITES(ASSET_VERSION INTEGER NOT NULL,SKU_ID varchar2(40),SITE_ID varchar2(40));