/* The table creation DDLs are created for country repository change. */
/* The table creation DDLs need to be executed in Pub servers. */
  
CREATE TABLE "SGS_SHIP_TO_COUNTRIES" 
   (	"SHIP_DETAILS_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"COUNTRY_ID" VARCHAR2(40 BYTE),
	"ASSET_VERSION" NUMBER(*,0) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
  
update USER_TAB_COMMENTS set COMMENTS = 'Table for Shipping Details to Country, One To Many mapping' where TABLE_NAME = 'SGS_SHIP_TO_COUNTRIES';
update USER_COL_COMMENTS set COMMENTS = 'Parent Shipping Details Id' where TABLE_NAME = 'SGS_SHIP_TO_COUNTRIES' and column_name = 'SHIP_DETAILS_ID';
update USER_COL_COMMENTS set COMMENTS = 'Child Countries Id' where TABLE_NAME = 'SGS_SHIP_TO_COUNTRIES' and column_name = 'COUNTRY_ID';