--user

  CREATE TABLE SGS_USER_HEALTH_CONCERN(
 PROFILE_ID varchar2(40),
 HEALTH_CONCERN_ID varchar2(40), PRIMARY KEY(PROFILE_ID,HEALTH_CONCERN_ID) using index );
 
   CREATE TABLE SGS_USER_INTERESTS(
 PROFILE_ID varchar2(40),
 USER_INTEREST_ID varchar2(40), PRIMARY KEY(PROFILE_ID,USER_INTEREST_ID) using index );
 
 
 ALTER TABLE dps_user ADD DOB_DAY varchar2(40);
ALTER TABLE dps_user ADD DOB_MONTH varchar2(40);
ALTER TABLE dps_user ADD DOB_YEAR varchar2(40);
ALTER TABLE dps_user ADD ABOUTUS varchar2(100);


 
commit;
--drop table SGS_HEALTH_CONCERNS_SITES;
--select * from SGS_HEALTH_CONCERNS_SITES;



