--17th Dec 2013

SET DEFINE OFF;
ALTER TABLE SGS_PRODUCT ADD DISPLAY_TITLE varchar2(254);
ALTER TABLE SGS_PRODUCT ADD PROD_DIRECTION CLOB;
ALTER TABLE SGS_PRODUCT ADD PROD_INGREDIENT CLOB;
ALTER TABLE SGS_PRODUCT ADD PROD_SOLUTION CLOB;
ALTER TABLE SGS_PRODUCT ADD SMALL_IMAGE varchar2(254);
ALTER TABLE SGS_PRODUCT ADD LARGE_IMAGE varchar2(254);
ALTER TABLE SGS_PRODUCT ADD MEDIUM_IMAGE varchar2(254);
ALTER TABLE SGS_PRODUCT ADD THUMBNAIL_IMAGE varchar2(254);
ALTER TABLE SGS_PRODUCT ADD PRODBACK_IMAGE varchar2(254);
ALTER TABLE SGS_SKU ADD DISPLAY_TITLE varchar2(254);
ALTER TABLE SGS_SKU ADD SMALL_IMAGE varchar2(254);
ALTER TABLE SGS_SKU ADD LARGE_IMAGE varchar2(254);
ALTER TABLE SGS_SKU ADD MEDIUM_IMAGE varchar2(254);
ALTER TABLE SGS_SKU ADD THUMBNAIL_IMAGE varchar2(254);

 CREATE TABLE SGS_PROD_BADGE(
 ASSET_VERSION 	INTEGER NOT NULL,
 BADGE_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(54), PRIMARY KEY(PRODUCT_ID,SITE_ID,ASSET_VERSION) using index
 );
 CREATE TABLE SGS_PRD_TESTI(
 ASSET_VERSION 	INTEGER NOT NULL,
 TESTI_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(54), PRIMARY KEY(PRODUCT_ID,SITE_ID,ASSET_VERSION) using index
 );
 
CREATE TABLE SGS_BADGES(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 BADGE_ID varchar2(40),
 BADGE_NAME varchar2(40),
 BADGE_DESCRIP varchar2(400),
 BADGE_IMAGE varchar2(254),
 LAST_MOD_DATE DATE	NULL,PRIMARY KEY(BADGE_ID,ASSET_VERSION) using index);

 
 CREATE TABLE SGS_BADGES_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 BADGE_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(BADGE_ID,SITE_ID,ASSET_VERSION) using index);
 
 
 CREATE TABLE SGS_TESTI_CONTAINER(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 TESTI_IDS varchar2(40),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(TESTI_IDS,ASSET_VERSION) using index);
 
 CREATE TABLE SGS_TESTI_LIST(
 ASSET_VERSION 		INTEGER NOT NULL,
 TESTI_ID varchar2(40),
 TESTI_IDS varchar2(40),
 SEQUENCE_NUM varchar2(40),PRIMARY KEY(TESTI_IDS,SEQUENCE_NUM,ASSET_VERSION) using index);
 
 CREATE TABLE SGS_TESTI(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 TESTI_ID varchar2(40),
 TESTI_NAME varchar2(40),
 TESTI_DESCRIP varchar2(400),
 TESTI_IMAGE varchar2(254),
 LAST_MOD_DATE DATE	NULL, PRIMARY KEY(TESTI_ID,ASSET_VERSION) using index);
 
 CREATE TABLE SGS_TESTI_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 TESTI_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(TESTI_ID,SITE_ID,ASSET_VERSION) using index);
 
 CREATE TABLE SGS_PRD_CHLDSKU_RELN(
 ASSET_VERSION 		INTEGER NOT NULL,
 SKUCH_PROD_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(SKUCH_PROD_ID,SITE_ID,ASSET_VERSION) using index);
 
 CREATE TABLE SGS_PRD_CHLDSKU_CONTAINER(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 SKUCH_PROD_IDS varchar2(40),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(SKUCH_PROD_IDS,ASSET_VERSION) using index);
 
 CREATE TABLE SGS_PRD_CHLDSKU_LIST(
 ASSET_VERSION 		INTEGER NOT NULL,
 SKUCH_PROD_IDS varchar2(40),
 CHILDSKU_ID varchar2(40),
 SEQUENCE_NUM varchar2(40),PRIMARY KEY(SKUCH_PROD_IDS,SEQUENCE_NUM,ASSET_VERSION) using index);
 
 
CREATE TABLE SGS_PROD_SOL(
 ASSET_VERSION 		INTEGER NOT NULL,
 SOL_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(SOL_ID,SITE_ID,ASSET_VERSION) using index);
 
 CREATE TABLE SGS_SOL_CONTAINER(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 SOL_IDS varchar2(40),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(SOL_IDS,ASSET_VERSION) using index);
 
 CREATE TABLE SGS_SOL_LIST(
 ASSET_VERSION 		INTEGER NOT NULL,
 SOL_ID varchar2(40),
 SOL_IDS varchar2(40),
 SEQUENCE_NUM varchar2(40),PRIMARY KEY(SOL_ID,SEQUENCE_NUM,ASSET_VERSION) using index );
 
 CREATE TABLE SGS_SOL_DETAILS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 SOL_ID varchar2(40),
 SOL_NAME varchar2(400),
 SOL_DESCRIP varchar2(400),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(SOL_ID,ASSET_VERSION) using index );
 CREATE TABLE SGS_SOL_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 SOL_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(SOL_ID,SITE_ID,ASSET_VERSION) using index );

 CREATE TABLE SGS_PROD_ING(
 ASSET_VERSION 		INTEGER NOT NULL,
 ING_ID varchar2(40),
 PRODUCT_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(ING_ID,SITE_ID,ASSET_VERSION) using index  );
 CREATE TABLE SGS_ING_CONTAINER(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 ING_IDS varchar2(40),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(ING_IDS,ASSET_VERSION) using index );
 
 CREATE TABLE SGS_ING_LIST(
 ASSET_VERSION 		INTEGER NOT NULL,
 ING_ID varchar2(40),
 ING_IDS varchar2(40),
 SEQUENCE_NUM varchar2(40),PRIMARY KEY(ING_ID,SEQUENCE_NUM,ASSET_VERSION) using index );
 
 CREATE TABLE SGS_ING_DETAILS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 ING_ID varchar2(40),
 ING_NAME varchar2(400),
 ING_DESCRIP varchar2(400),
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(ING_ID,ASSET_VERSION) using index );
 CREATE TABLE SGS_ING_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 ING_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(ING_ID,SITE_ID,ASSET_VERSION) using index );
 
CREATE TABLE COMVITA_PROD_SITE_TRANSLATIONS(
ASSET_VERSION 		INTEGER NOT NULL,
PRODUCT_ID  VARCHAR2(40),
TRANSLATION_ID VARCHAR2(80),PRIMARY KEY(PRODUCT_ID,TRANSLATION_ID) using index );
 
CREATE TABLE COMVITA_PROD_TRANSLATIONS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
TRANSLATION_ID                   VARCHAR2(80), 
SITE_ID                          VARCHAR2(40),  
LOCALE_ID                        VARCHAR2(40), 
DISPLAY_NAME                     VARCHAR2(254), 
DESCRIPTION                     VARCHAR2(1200),
TITLE                           VARCHAR2(40),
DIR_DESC                        VARCHAR2(1200),
SOL_DESC                        VARCHAR2(1200),
ING_ESC                         VARCHAR2(1200),      
PRICE_RANGEDESC                 VARCHAR2(1200),      
WEBONLY                         NUMBER(1),
WEBOFFERED          			NUMBER(1),
PRODDISABLE                     NUMBER(1),
SKULOWPRICE                     VARCHAR2(40),
SKUHIGHPRICE                    VARCHAR2(40),
LAST_MOD_DATE DATE	NULL,PRIMARY KEY(SITE_ID,TRANSLATION_ID,ASSET_VERSION) using index );
 
 
--------------------------------------------24th Dec 2013



CREATE SEQUENCE price_id
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1000
  INCREMENT BY 1
  CACHE 20;

create table temp_sku (
sku_id varchar2(100)
);

Insert into temp_sku (SKU_ID) values ('120');
Insert into temp_sku (SKU_ID) values ('EN102');
Insert into temp_sku (SKU_ID) values ('EN103');
Insert into temp_sku (SKU_ID) values ('EN169');
Insert into temp_sku (SKU_ID) values ('EXP10077');
Insert into temp_sku (SKU_ID) values ('EXP153');
Insert into temp_sku (SKU_ID) values ('EXP10073  ');
Insert into temp_sku (SKU_ID) values ('EXP10074');
Insert into temp_sku (SKU_ID) values ('EXP10070');
Insert into temp_sku (SKU_ID) values ('EXP10071');
Insert into temp_sku (SKU_ID) values ('EN110');
Insert into temp_sku (SKU_ID) values ('EN111');
Insert into temp_sku (SKU_ID) values ('EN112');
Insert into temp_sku (SKU_ID) values ('EN361');
Insert into temp_sku (SKU_ID) values ('EN373');
Insert into temp_sku (SKU_ID) values ('EN555');
Insert into temp_sku (SKU_ID) values ('EN10007');
Insert into temp_sku (SKU_ID) values ('EN388');
Insert into temp_sku (SKU_ID) values ('499');
Insert into temp_sku (SKU_ID) values ('488');
Insert into temp_sku (SKU_ID) values ('473');
Insert into temp_sku (SKU_ID) values ('476');
Insert into temp_sku (SKU_ID) values ('498');
Insert into temp_sku (SKU_ID) values ('332');
Insert into temp_sku (SKU_ID) values ('333');
Insert into temp_sku (SKU_ID) values ('334');
Insert into temp_sku (SKU_ID) values ('335');
Insert into temp_sku (SKU_ID) values ('623');
Insert into temp_sku (SKU_ID) values ('307');
Insert into temp_sku (SKU_ID) values ('EN414');
Insert into temp_sku (SKU_ID) values ('414');
Insert into temp_sku (SKU_ID) values ('644');
Insert into temp_sku (SKU_ID) values ('EN644');
Insert into temp_sku (SKU_ID) values ('EN343');
Insert into temp_sku (SKU_ID) values ('343');


PROCEDURE Create_PriceUK ()
IS
 BEGIN
 		FOR skuId IN (SELECT SKU_ID  FROM temp_sku)
		LOOP
			Insert into DCS_PRICE (SEC_ASSET_VERSION,ASSET_VERSION,WORKSPACE_ID,BRANCH_ID,IS_HEAD,VERSION_DELETED,VERSION_EDITABLE,PRED_VERSION,CHECKIN_DATE,PRICE_ID,VERSION,PRICE_LIST,PRODUCT_ID,SKU_ID,PARENT_SKU_ID,PRICING_SCHEME,LIST_PRICE,COMPLEX_PRICE) values (1,1,'DC110637','10100',1,0,0,null,to_timestamp('24-DEC-13 05.46.52.468000000 PM','DD-MON-RR HH.MI.SS.FF AM'),price_id.nextval,2,'comvitauklplist9001','',skuId.sku_id,null,0,price_id.nextval,null);
            Insert into SGS_PRICE (ASSET_VERSION,PRICE_ID,LAST_MOD_DATE) values (1,price_id.nextval-1,to_timestamp('03-JAN-14 05.46.52.468000000 PM','DD-MON-RR HH.MI.SS.FF AM'));

		END LOOP;
 	
END Create_PriceUK;

/
show error
commit;  


-------------------------- 27th Dec 2013

ALTER TABLE sgs_sol_list DROP PRIMARY KEY;
ALTER TABLE sgs_ing_list DROP PRIMARY KEY;
ALTER TABLE SGS_PROD_SOL DROP PRIMARY KEY;
ALTER TABLE SGS_PROD_ING DROP PRIMARY KEY;
ALTER TABLE SGS_PRD_CHLDSKU_RELN DROP PRIMARY KEY;
ALTER TABLE COMVITA_PROD_SITE_TRANSLATIONS DROP PRIMARY KEY;
ALTER TABLE COMVITA_PROD_TRANSLATIONS  MODIFY title varchar2(254);
commit;


---------------------------2nd Jan 2014



CREATE TABLE "SGS_SHIPPING_METHOD_DETAILS" 
   (	"SHIP_DETAILS_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"SHIP_METHOD_NAME" VARCHAR2(254 BYTE), 
	"SHIP_METHOD_DESCRIPTION" VARCHAR2(254 BYTE), 
	"SITE_ID" VARCHAR2(40 BYTE), 
	"STATE_ID" VARCHAR2(20 BYTE), 
	"COUNTRY_ID" VARCHAR2(40 BYTE), 
	"PRICE" NUMBER(10,2), 
	"SHIP_DUTY" NUMBER(10,2), 
	"FREE_SHIP_THRESHOLD" NUMBER(10,2), 
	"MIN_DAYS_TO_SHIP" NUMBER(*,0), 
	"MAX_DAYS_TO_SHIP" NUMBER(*,0), 
	"CUT_OFF_TIME" DATE,
	"LOWER_LIMIT" NUMBER(10,2), 
	"UPPER_LIMIT" NUMBER(10,2),
 	"ASSET_VERSION" NUMBER(*,0) NOT NULL ENABLE, 
	"WORKSPACE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"BRANCH_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IS_HEAD" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_DELETED" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_EDITABLE" NUMBER(1,0) NOT NULL ENABLE, 
	"PRED_VERSION" NUMBER(*,0), 
	"CHECKIN_DATE" TIMESTAMP (6)
	);
  
CREATE TABLE "SGS_COUNTRIES" 
   (	"COUNTRY_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(254 BYTE), 
	"SHIPPING_FLAG" NUMBER(1,0),
	"ASSET_VERSION" NUMBER(*,0) NOT NULL ENABLE, 
	"WORKSPACE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"BRANCH_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"IS_HEAD" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_DELETED" NUMBER(1,0) NOT NULL ENABLE, 
	"VERSION_EDITABLE" NUMBER(1,0) NOT NULL ENABLE, 
	"PRED_VERSION" NUMBER(*,0), 
	"CHECKIN_DATE" TIMESTAMP (6)
	) ;
  
CREATE TABLE "SGS_COUNTRY_STATES" 
   (	"COUNTRY_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"STATE_ID" VARCHAR2(20 BYTE),
	"ASSET_VERSION" NUMBER(*,0) NOT NULL ENABLE
	)  ;

CREATE TABLE "SGS_COUNTRIES_LIST" 
   (	"SITE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"COUNTRY_ID" VARCHAR2(40 BYTE),
	"ASSET_VERSION" NUMBER(*,0) NOT NULL ENABLE
   ) ;



----------------------------------3rd Jan 2014


ALTER TABLE SGS_PROD_SOL DROP PRIMARY KEY;
ALTER TABLE SGS_PROD_ING DROP PRIMARY KEY;
commit;


CREATE SEQUENCE price_id
  MINVALUE 1
  MAXVALUE 999999999999999999999999999
  START WITH 1000
  INCREMENT BY 1
  CACHE 20;

Insert into temp_sku (SKU_ID) values ('SJP001');
Insert into temp_sku (SKU_ID) values ('SJP002');
Insert into temp_sku (SKU_ID) values ('SJP003');
Insert into temp_sku (SKU_ID) values ('SJP004');
Insert into temp_sku (SKU_ID) values ('SJP005');
Insert into temp_sku (SKU_ID) values ('SJP006');
Insert into temp_sku (SKU_ID) values ('SJP007');
Insert into temp_sku (SKU_ID) values ('SJP008');
Insert into temp_sku (SKU_ID) values ('SJP009');
Insert into temp_sku (SKU_ID) values ('SJP010');
Insert into temp_sku (SKU_ID) values ('SJP011');
Insert into temp_sku (SKU_ID) values ('SJP012');
Insert into temp_sku (SKU_ID) values ('SJP013');
Insert into temp_sku (SKU_ID) values ('SJP014');
Insert into temp_sku (SKU_ID) values ('SJP015');
Insert into temp_sku (SKU_ID) values ('SJP016');
Insert into temp_sku (SKU_ID) values ('SJP017');
Insert into temp_sku (SKU_ID) values ('SJP018');
Insert into temp_sku (SKU_ID) values ('SJP019');
Insert into temp_sku (SKU_ID) values ('SJP020');
Insert into temp_sku (SKU_ID) values ('SJP021');
Insert into temp_sku (SKU_ID) values ('SJP022');
Insert into temp_sku (SKU_ID) values ('SJP023');
Insert into temp_sku (SKU_ID) values ('SJP024');
Insert into temp_sku (SKU_ID) values ('SJP025');
Insert into temp_sku (SKU_ID) values ('SJP026');
Insert into temp_sku (SKU_ID) values ('SJP027');
Insert into temp_sku (SKU_ID) values ('SJP028');
Insert into temp_sku (SKU_ID) values ('SJP029');
Insert into temp_sku (SKU_ID) values ('SJP030');
Insert into temp_sku (SKU_ID) values ('SJP031');
Insert into temp_sku (SKU_ID) values ('SJP032');
Insert into temp_sku (SKU_ID) values ('SJP033');
Insert into temp_sku (SKU_ID) values ('SJP034');
Insert into temp_sku (SKU_ID) values ('SJP035');
Insert into temp_sku (SKU_ID) values ('SJP036');
  
  
PROCEDURE Create_Price ()
IS
 BEGIN
 		FOR skuId IN (SELECT SKU_ID  FROM temp_sku)
		LOOP
			Insert into DCS_PRICE (SEC_ASSET_VERSION,ASSET_VERSION,WORKSPACE_ID,BRANCH_ID,IS_HEAD,VERSION_DELETED,VERSION_EDITABLE,PRED_VERSION,CHECKIN_DATE,PRICE_ID,VERSION,PRICE_LIST,PRODUCT_ID,SKU_ID,PARENT_SKU_ID,PRICING_SCHEME,LIST_PRICE,COMPLEX_PRICE) values (1,1,'DC110637','10100',1,0,0,null,to_timestamp('03-JAN-14 05.46.52.468000000 PM','DD-MON-RR HH.MI.SS.FF AM'),price_id.nextval,2,'comvitajplplist9001','',skuId.sku_id,null,0,price_id.nextval,null);
            Insert into SGS_PRICE (ASSET_VERSION,PRICE_ID,LAST_MOD_DATE) values (1,price_id.nextval-1,to_timestamp('03-JAN-14 05.46.52.468000000 PM','DD-MON-RR HH.MI.SS.FF AM'));

		END LOOP;
 	
END Create_Price;

/
show error
Commit;  


----------------------------------8th Jan 2014

CREATE TABLE SGS_PROD_OTHING(ASSET_VERSION INTEGER NOT NULL,OTHING_ID varchar2(40),PRODUCT_ID varchar2(40),SITE_ID varchar2(40));

CREATE TABLE SGS_OTHING_CONTAINER(ASSET_VERSION INTEGER NOT NULL,
WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
BRANCH_ID 		VARCHAR2(40) NOT NULL,
IS_HEAD 		NUMBER(1) NOT NULL,
VERSION_DELETED 	NUMBER(1) NOT NULL,
VERSION_EDITABLE 	NUMBER(1) NOT NULL,
PRED_VERSION 		INTEGER NULL,
CHECKIN_DATE 		TIMESTAMP NULL,
OTHING_IDS varchar2(40),
LAST_MOD_DATE DATE NULL);

CREATE TABLE SGS_OTHING_LIST(ASSET_VERSION INTEGER NOT NULL,
OTHING_ID varchar2(40),
OTHING_IDS varchar2(40),
SEQUENCE_NUM varchar2(40));

CREATE TABLE SGS_OTHING_SITES(ASSET_VERSION INTEGER NOT NULL,
OTHING_ID varchar2(40),
SITE_ID varchar2(40));

CREATE TABLE SGS_OTHING_DETAILS(ASSET_VERSION INTEGER NOT NULL,
WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
BRANCH_ID 		VARCHAR2(40) NOT NULL,
IS_HEAD 		NUMBER(1) NOT NULL,
VERSION_DELETED 	NUMBER(1) NOT NULL,
VERSION_EDITABLE 	NUMBER(1) NOT NULL,
PRED_VERSION 		INTEGER NULL,
CHECKIN_DATE 		TIMESTAMP NULL,
OTHING_ID VARCHAR2(40),
BACK_IMAGE_LARGE VARCHAR2(100),
OTHING_NAME varchar2(400),
OTHING_LONGDESCRIP CLOB,
DISPLAY_IMAGE_SMALL VARCHAR2(100),
DISPLAY_TITLE varchar2(400),
DISPLAY_DESC CLOB,
LAST_MOD_DATE DATE	NULL);


ALTER TABLE SGS_ING_DETAILS drop column ING_DESCRIP;
ALTER TABLE SGS_ING_DETAILS ADD ING_DESCRIP CLOB ;
ALTER TABLE SGS_ING_DETAILS ADD BACK_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD ING_IMAGE_DESCRIP CLOB;
ALTER TABLE SGS_ING_DETAILS ADD ING_DESCRIP2 CLOB;
ALTER TABLE SGS_ING_DETAILS ADD ING_VIDEO VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD BADGE_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD ING_CERTI_DESCRIP CLOB;
ALTER TABLE SGS_ING_DETAILS ADD ING_CERTI_TITLE VARCHAR2(4000);
ALTER TABLE SGS_ING_DETAILS ADD DISPLAY_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_ING_DETAILS ADD DISPLAY_TITLE VARCHAR2(4000);
ALTER TABLE SGS_ING_DETAILS ADD DISPLAY_DESC CLOB;

ALTER TABLE SGS_SOL_DETAILS drop column SOL_DESCRIP;
ALTER TABLE SGS_SOL_DETAILS ADD SOL_DESCRIP CLOB ;
ALTER TABLE SGS_SOL_DETAILS ADD BACK_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_SOL_DETAILS ADD IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_SOL_DETAILS ADD SOL_DESCRIP2 CLOB;
ALTER TABLE SGS_SOL_DETAILS ADD SOL_DESCRIP3 CLOB;
ALTER TABLE SGS_SOL_DETAILS ADD SYMPTOMS CLOB;
ALTER TABLE SGS_SOL_DETAILS ADD DISPLAY_IMAGE_LARGE VARCHAR2(100);
ALTER TABLE SGS_SOL_DETAILS ADD DISPLAY_TITLE VARCHAR2(4000);
ALTER TABLE SGS_SOL_DETAILS ADD DISPLAY_DESC CLOB;

-----------------------------------10th Jan 2014


CREATE TABLE "SGS_SHIP_TO_COUNTRIES" 
   (	"SHIP_DETAILS_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	"COUNTRY_ID" VARCHAR2(40 BYTE),
	"ASSET_VERSION" NUMBER(*,0) NOT NULL ENABLE
   );
  
update USER_TAB_COMMENTS set COMMENTS = 'Table for Shipping Details to Country, One To Many mapping' where TABLE_NAME = 'SGS_SHIP_TO_COUNTRIES';
update USER_COL_COMMENTS set COMMENTS = 'Parent Shipping Details Id' where TABLE_NAME = 'SGS_SHIP_TO_COUNTRIES' and column_name = 'SHIP_DETAILS_ID';
update USER_COL_COMMENTS set COMMENTS = 'Child Countries Id' where TABLE_NAME = 'SGS_SHIP_TO_COUNTRIES' and column_name = 'COUNTRY_ID';
Commit;

-----------------------------------13th Jan 2014

ALTER TABLE
   SGS_SITE_ATTRIBUTES
ADD (
	tax_type 	varchar2(30)	NULL,
	tax_rate 	number(6, 2)	NULL
	 
);
 

ALTER TABLE
   SGS_SKU
ADD (
	is_tax_applicable 	number(1)	NULL,
	CHECK (is_tax_applicable IN (0, 1))
); 



ALTER TABLE SGS_PRODUCT ADD FREE_ITEM_PRODUCT number(1);
ALTER TABLE COMVITA_PROD_TRANSLATIONS ADD FREE_ITEM_PRODUCT number(1);


ALTER TABLE COMVITA_PROD_TRANSLATIONS ADD LARGE_IMAGE VARCHAR2(100);
ALTER TABLE COMVITA_PROD_TRANSLATIONS ADD SMALL_IMAGE VARCHAR2(100);
ALTER TABLE COMVITA_PROD_TRANSLATIONS ADD MEDIUM_IMAGE VARCHAR2(100);
ALTER TABLE COMVITA_PROD_TRANSLATIONS ADD THUMBNAIL_IMAGE VARCHAR2(100);


----------------------------------14th Jan 2014


Drop Table SGS_PRD_CHLDSKU_RELN;
Drop Table SGS_PRD_CHLDSKU_CONTAINER;
Drop Table SGS_PRD_CHLDSKU_LIST;
CREATE TABLE SGS_SKU_SITES(ASSET_VERSION INTEGER NOT NULL,SKU_ID varchar2(40),SITE_ID varchar2(40));



-------------------------------------15th jan 2014

ALTER TABLE
   SGS_SITE_ATTRIBUTES
ADD (
	is_tax_applicable 	number(1)	NULL,
	CHECK (is_tax_applicable IN (0, 1))
	 	 
);


----------------------------------16th jan 2014

drop table SGS_TESTI;
drop table SGS_TESTI_LIST;
drop table SGS_TESTI_CONTAINER;
drop table SGS_PRD_TESTI;
drop table SGS_TESTI_SITES;

CREATE TABLE SGS_TESTIMONIAL (
	testimonial_id 		varchar2(254)	NOT NULL,
	asset_version 		INTEGER	NOT NULL,
	testimonial_creator_name varchar2(254)	NULL,
	testimonial_description CLOB	NULL,
	testimonial_image 	varchar2(254)	NULL,
	testimonial_title 	varchar2(254)	NULL,
	testimonial_creator_country varchar2(254)	NULL,
	testimonial_date 	DATE	NULL,
	last_mod_date 		DATE	NULL,
	version_deleted 	number(1)	NULL,
	version_editable 	number(1)	NULL,
	pred_version 		INTEGER	NULL,
	workspace_id 		varchar2(254)	NULL,
	branch_id 		varchar2(254)	NULL,
	is_head 		number(1)	NULL,
	checkin_date 		DATE	NULL,
	CHECK (version_deleted IN (0, 1)),
	CHECK (version_editable IN (0, 1)),
	CHECK (is_head IN (0, 1)),
	PRIMARY KEY(testimonial_id, asset_version)
);

CREATE TABLE SGS_TESTIMONIAL_SITES (
	testimonial_id 		varchar2(254)	NOT NULL,
	asset_version 		INTEGER	NOT NULL,
	site_id 		varchar2(254)	NOT NULL,
	PRIMARY KEY(testimonial_id, asset_version, site_id)
);

CREATE TABLE SGS_TESTIMONIAL_CONTAINER (
	testimonial_ids 	varchar2(254)	NOT NULL,
	asset_version 		INTEGER	NOT NULL,
	last_mod_date 		DATE	NULL,
	version_deleted 	number(1)	NULL,
	version_editable 	number(1)	NULL,
	pred_version 		INTEGER	NULL,
	workspace_id 		varchar2(254)	NULL,
	branch_id 		varchar2(254)	NULL,
	is_head 		number(1)	NULL,
	checkin_date 		DATE	NULL,
	CHECK (version_deleted IN (0, 1)),
	CHECK (version_editable IN (0, 1)),
	CHECK (is_head IN (0, 1)),
	PRIMARY KEY(testimonial_ids, asset_version)
);

CREATE TABLE SGS_TESTIMONIAL_LIST (
	testimonial_ids 	varchar2(254)	NOT NULL,
	asset_version 		INTEGER	NOT NULL,
	sequence_num 		INTEGER	NOT NULL,
	testimonial_id 		varchar2(254)	NULL,
	PRIMARY KEY(testimonial_ids, asset_version, sequence_num)
);

CREATE TABLE SGS_PRD_TESTIMONIAL (
	product_id 		varchar2(254)	NOT NULL,
	asset_version 		INTEGER	NOT NULL,
	site_id 		varchar2(254)	NOT NULL,
	testimonial_id 		varchar2(254)	NULL,
	PRIMARY KEY(product_id, asset_version, site_id)
);

 

----------------------------------27th Jan 2014

--userInterests

CREATE TABLE SGS_PRODUCT_INTERESTS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 INTEREST_ID varchar2(40) NOT NULL,
 INTEREST_NAME varchar2(100),
 INTEREST_VALUE varchar2(100), 
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(INTEREST_ID,ASSET_VERSION) using index );


commit;


 CREATE TABLE SGS_PRODUCT_INTERESTS_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 INTEREST_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(INTEREST_ID,SITE_ID,ASSET_VERSION) using index );
 
commit;


---------------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------------

--userHealthConcerns

CREATE TABLE SGS_HEALTH_CONCERNS(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 HEALTH_CONCERN_ID varchar2(40) NOT NULL,
 HEALTH_CONCERN_NAME varchar2(100),
 HEALTH_CONCERN_VALUE varchar2(100), 
 LAST_MOD_DATE DATE	NULL ,PRIMARY KEY(HEALTH_CONCERN_ID,ASSET_VERSION) using index );

commit;
 
CREATE TABLE SGS_HEALTH_CONCERNS_SITES(
 ASSET_VERSION 		INTEGER NOT NULL,
 HEALTH_CONCERN_ID varchar2(40),
 SITE_ID varchar2(40), PRIMARY KEY(HEALTH_CONCERN_ID,SITE_ID,ASSET_VERSION) using index );

commit;


----------------------------------29th Jan 2014
--product

CREATE TABLE SGS_PROD_REL_BUNDLES
  (
   ASSET_VERSION INTEGER NOT NULL,
   BUNDLE_PRODUCT_ID varchar2(40),
   PRODUCT_ID varchar2(40),
   SITE_ID varchar2(40), PRIMARY KEY(BUNDLE_PRODUCT_ID,SITE_ID,ASSET_VERSION) using index
   );


--------------------------30th Jan 2014
CREATE TABLE sgs_paypal_pay_grp
  ( payment_group_id VARCHAR2(40),
    payer_id VARCHAR2(40),
    payer_email      VARCHAR2(40),
    payer_status         VARCHAR2(40),	
	payer_name VARCHAR2(40),
    payer_country_code VARCHAR2(40),
    payer_biz VARCHAR2(40),
    buyer_Email VARCHAR2(40),	
	CONSTRAINT PK_SGS_PAYPAL_PG_ID PRIMARY KEY(payment_group_id)
   );
      
   
   CREATE TABLE SGS_paypal_status
   ( status_id VARCHAR2(40),
     transaction_id VARCHAR2(40),
     payment_Req_id      VARCHAR2(40),
     payment_type         VARCHAR2(40),	
	 payment_date date,  
	 gross_amt number(10,2),
	 tax_amt number(10,2),
	 fraud_Details VARCHAR2(40),
	 payment_status VARCHAR2(40),
	 pending_reason VARCHAR2(40),
	 reason_code VARCHAR2(40),
	 hold_decision VARCHAR2(40),
	 billing_agree_id VARCHAR2(40),
	 CONSTRAINT PK_SGS_PAYPAL_STATUS_ID PRIMARY KEY(status_id)
   );



--------------------------30th Jan 2014

ALTER TABLE SGS_ING_DETAILS ADD image_alt_text varchar2(254);

ALTER TABLE SGS_OTHING_DETAILS ADD image_alt_text varchar2(254);

ALTER TABLE SGS_SOL_DETAILS ADD image_alt_text varchar2(254);
commit; 

--------------------------31st Jan 2014

--user

CREATE TABLE SGS_USER_HEALTH_CONCERN(
ASSET_VERSION INTEGER NOT NULL,
PROFILE_ID varchar2(40),
HEALTH_CONCERN_ID varchar2(40), PRIMARY KEY(PROFILE_ID,HEALTH_CONCERN_ID,ASSET_VERSION) using index );
 
 
CREATE TABLE SGS_USER_INTERESTS(
ASSET_VERSION INTEGER NOT NULL,
PROFILE_ID varchar2(40),
USER_INTEREST_ID varchar2(40), PRIMARY KEY(PROFILE_ID,USER_INTEREST_ID,ASSET_VERSION) using index );
 
 
ALTER TABLE dps_user ADD DOB_DAY varchar2(40);
ALTER TABLE dps_user ADD DOB_MONTH varchar2(40);
ALTER TABLE dps_user ADD DOB_YEAR varchar2(40);
ALTER TABLE dps_user ADD ABOUTUS varchar2(100);

commit;


--------------------------04th Feb 2014

--userHearAboutUs

CREATE TABLE SGS_HEAR_ABOUT_US(
 ASSET_VERSION 		INTEGER NOT NULL,
 WORKSPACE_ID 		VARCHAR2(40) NOT NULL,
 BRANCH_ID 		    VARCHAR2(40) NOT NULL,
 IS_HEAD 		    NUMBER(1) NOT NULL,
 VERSION_DELETED 	NUMBER(1) NOT NULL,
 VERSION_EDITABLE 	NUMBER(1) NOT NULL,
 PRED_VERSION 		INTEGER NULL,
 CHECKIN_DATE 		TIMESTAMP NULL,
 HEAR_ABOUT_US_ID varchar2(40) NOT NULL,
 HEAR_ABOUT_US_NAME varchar2(100),
 HEAR_ABOUT_US_VALUE varchar2(100), 
 LAST_MOD_DATE DATE NULL ,PRIMARY KEY(HEAR_ABOUT_US_ID,ASSET_VERSION) using index );


commit;

CREATE TABLE SGS_HEAR_ABOUT_US_SITES(
ASSET_VERSION 		INTEGER NOT NULL,
HEAR_ABOUT_US_ID varchar2(40),
SITE_ID varchar2(40), PRIMARY KEY(HEAR_ABOUT_US_ID,SITE_ID,ASSET_VERSION) using index );
 
commit;


--------------------------05th Feb 2014
--user
ALTER TABLE dps_user ADD USER_GENDER varchar2(40);
commit;


--------------------------06th Feb 2014
Alter table SGS_REL_CONFIG_KEY_VALUE MODIFY CONFIG_VALUE varchar2(1000);
commit;


--------------------------11th Feb 2014 - Ajay Sharma
-- Update statement for switchA and switchB and Publishing and staging
UPDATE SGS_SHIPPING_METHOD_DETAILS SET cut_off_time = SYSDATE-379 ;
UPDATE SGS_SHIPPING_METHOD_DETAILS SET  max_days_to_ship=9 WHERE max_days_to_ship is NULL;
commit;

--------------------------13th Feb 2014 - Shreshth Sandilya
ALTER TABLE sgs_hrd_ship_group ADD INVOICE_NO varchar2(40);
commit;


--------------------------20th Feb 2014 - Sunil Kumar 8 <skumar134@sapient.com>
-- THIS SQL NEED TO BE EXECUTED ON SWITCH_A,SWITCH_B AND STAGING ENVIRONMENT.

CREATE TABLE SGS_COD_PAY_GRP (
 ASSET_VERSION 	INTEGER NOT NULL,
 PAYMENT_GROUP_ID VARCHAR2(254),
 COD_NUMBER VARCHAR2(254) NULL,
 COD_EMAIL VARCHAR2(254) NULL,
 COD_STATUS VARCHAR2(254) NULL,
 COD_NAME VARCHAR2(254) NULL,
 COD_COUNTRY_CODE VARCHAR2(254) NULL,
 AMOUNT NUMBER(28, 20) NULL,
 PRIMARY KEY(PAYMENT_GROUP_ID,ASSET_VERSION) );

CREATE TABLE SGS_COD_STATUS (
 ASSET_VERSION 	INTEGER NOT NULL,
 STATUS_ID VARCHAR2(254),
 AUTH_CODE VARCHAR2(254) NULL,
 TRACE_NUMBER VARCHAR2(254) NULL,
 AUTH_RESPONSE_CODE VARCHAR2(254) NULL,
 AMOUNT NUMBER(28, 20) NULL, 
 TRANSACTION_ID VARCHAR2(254) NULL,
 PRIMARY KEY(STATUS_ID,ASSET_VERSION) );

CREATE TABLE SGS_DEF_PAY_GRP (
 ASSET_VERSION 	INTEGER NOT NULL,
 PAYMENT_GROUP_ID VARCHAR2(254),
 DEF_NUMBER VARCHAR2(254) NULL,
 DEF_EMAIL VARCHAR2(254) NULL,
 DEF_STATUS VARCHAR2(254) NULL,
 DEF_NAME VARCHAR2(254) NULL,
 COD_COUNTRY_CODE VARCHAR2(254) NULL,
 AMOUNT NUMBER(28, 20) NULL, PRIMARY KEY(PAYMENT_GROUP_ID,ASSET_VERSION) );
 
 CREATE TABLE SGS_DEF_STATUS (
 ASSET_VERSION 	INTEGER NOT NULL,
 STATUS_ID VARCHAR2(254), 
 AUTH_CODE VARCHAR2(254) NULL,
 TRACE_NUMBER VARCHAR2(254) NULL,
 AUTH_RESPONSE_CODE VARCHAR2(254) NULL,
 AMOUNT NUMBER(28, 20) NULL,
 TRANSACTION_ID VARCHAR2(254) NULL,
 PRIMARY KEY(STATUS_ID,ASSET_VERSION) );
 COMMIT;
 
--------------------------Mar 12th 2014 - Sanam Jain <sjain82@sapient.com>
-- THIS SQL NEED TO BE EXECUTED ON SWITCH_A,SWITCH_B, PUB AND STAGING ENVIRONMENT.

ALTER TABLE SGS_COUNTRIES ADD ISOcode varchar2(30) NULL;
commit;

--------------------------Mar 13th 2014 - Neeraj Garg 2 <ngarg13@sapient.com>

ALTER TABLE SGS_DPS_USER ADD (logged_in NUMBER(1,0) , migrated_account NUMBER(1,0) );
