ALTER TABLE sgs_sol_list DROP PRIMARY KEY;
ALTER TABLE sgs_ing_list DROP PRIMARY KEY;
ALTER TABLE SGS_PROD_SOL DROP PRIMARY KEY;
ALTER TABLE SGS_PROD_ING DROP PRIMARY KEY;
ALTER TABLE SGS_PRD_CHLDSKU_RELN DROP PRIMARY KEY;
ALTER TABLE COMVITA_PROD_SITE_TRANSLATIONS DROP PRIMARY KEY;
ALTER TABLE COMVITA_PROD_TRANSLATIONS  MODIFY title varchar2(254);
commit;