-- THIS SQL NEED TO BE EXECUTED ON SWITCH_A,SWITCH_B AND STAGING ENVIRONMENT.

CREATE TABLE SGS_COD_PAY_GRP (
 ASSET_VERSION 	INTEGER NOT NULL,
 PAYMENT_GROUP_ID VARCHAR2(254),
 COD_NUMBER VARCHAR2(254) NULL,
 COD_EMAIL VARCHAR2(254) NULL,
 COD_STATUS VARCHAR2(254) NULL,
 COD_NAME VARCHAR2(254) NULL,
 COD_COUNTRY_CODE VARCHAR2(254) NULL,
 AMOUNT NUMBER(28, 20) NULL,
 PRIMARY KEY(PAYMENT_GROUP_ID,ASSET_VERSION) );

CREATE TABLE SGS_COD_STATUS (
 ASSET_VERSION 	INTEGER NOT NULL,
 STATUS_ID VARCHAR2(254),
 AUTH_CODE VARCHAR2(254) NULL,
 TRACE_NUMBER VARCHAR2(254) NULL,
 AUTH_RESPONSE_CODE VARCHAR2(254) NULL,
 AMOUNT NUMBER(28, 20) NULL, 
 TRANSACTION_ID VARCHAR2(254) NULL,
 PRIMARY KEY(STATUS_ID,ASSET_VERSION) );

CREATE TABLE SGS_DEF_PAY_GRP (
 ASSET_VERSION 	INTEGER NOT NULL,
 PAYMENT_GROUP_ID VARCHAR2(254),
 DEF_NUMBER VARCHAR2(254) NULL,
 DEF_EMAIL VARCHAR2(254) NULL,
 DEF_STATUS VARCHAR2(254) NULL,
 DEF_NAME VARCHAR2(254) NULL,
 COD_COUNTRY_CODE VARCHAR2(254) NULL,
 AMOUNT NUMBER(28, 20) NULL, PRIMARY KEY(PAYMENT_GROUP_ID,ASSET_VERSION) );
 
 CREATE TABLE SGS_DEF_STATUS (
 ASSET_VERSION 	INTEGER NOT NULL,
 STATUS_ID VARCHAR2(254), 
 AUTH_CODE VARCHAR2(254) NULL,
 TRACE_NUMBER VARCHAR2(254) NULL,
 AUTH_RESPONSE_CODE VARCHAR2(254) NULL,
 AMOUNT NUMBER(28, 20) NULL,
 TRANSACTION_ID VARCHAR2(254) NULL,
 PRIMARY KEY(STATUS_ID,ASSET_VERSION) );
 COMMIT ;
-- DROP TABLE SGS_COD_STATUS;
-- DROP TABLE SGS_COD_PAY_GRP;
-- DROP TABLE SGS_DEF_STATUS;
-- DROP TABLE SGS_DEF_PAY_GRP;